# Generated by Django 3.1.6 on 2021-06-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210625_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='project-document/', verbose_name='Project Document'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project-file/', verbose_name='Project File'),
        ),
    ]
